### ISSUE TITLE
Questions / Dynamic ProductID

### ISSUE THREAD

**Issue by JakeHenshall** [ducdev/aliexscrape#1]
Hi,

This is great.

1. What would be the best way to do this? What I would like to happen is when a user clicks a button that is related to a Product and a Product ID the ID gets pushed into this part AliexScrape('XXXXXXXXX') and then spits out a JSON file with all of the data related to each product.

2. Is there a way to grab all Shipping Methods. I have attached a screenshot.

![shipping methods](https://user-images.githubusercontent.com/4720782/44141934-81da3c3e-a076-11e8-97b1-f839a1f3dcde.png)

Any help would be really appreciated.

Thanks, Jake.

**Comment by ducdev** [comment]
1. Sorry I did not understand your request.

2. I tried but unluckily I did not win on getting the shipping method, and in fact the shipping method pricing may be different when you scrape the product and when someone actually purchase, it's calculated in real-time I guess. I would suggest you to apply free shipping and include the cost of shipping in your up pricing strategy.

**Comment by JakeHenshall** [comment]
@ducdev 

Thanks for responding.

1. So say that I have a single button. When the user clicks that button the ProductID gets put into a variable and the button will run the AliexScrape get the data and store that data into a JSON file.

2. Thank you for trying :) 👍 

How would I go about doing that?

Thanks, Jake.
