### ISSUE TITLE
Aliexpress blocking

### ISSUE THREAD

**Issue by drwasho** [ducdev/aliexscrape#3]
Have you tested how many listings you can scrape before Aliexpress attempts to block you?

**Comment by ducdev** [comment]
It depends, I think. Sometimes you need a lot of proxies for massive scraping.

**Comment by wakawaka54** [comment]
I'm the developer behind Aliseeks.com , we offer an API which can help you get product details. I recommend you take a look at our [API Documentation.](https://docs.aliseeks.com/api/)

**Comment by ducdev** [comment]
> I'm the developer behind Aliseeks.com , we offer an API which can help you get product details. I recommend you take a look at our [API Documentation.](https://docs.aliseeks.com/api/)

I'll have a look soon.
